EasyTest/urls.py
from django.contrib import admin
# from django.urls import path
from django.conf.urls import include
# from EasyTest.views import index
from EasyTest import views
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

admin.site.site_header = 'EasyTest-后台管理'
admin.site.site_title = 'EasyTest-Manage'

urlpatterns = [

    url(r'admin/', admin.site.urls),
    url(r'^$', view=views.index, name="index"),
    url(r'index/$', view=views.index, name="index"),
    url(r'index_data/$', view=views.index_data, name="index_data"),
    url(r'^login_action/$', view=views.login_action, name='login_action'),
    url(r'^change_password/$', view=views.change_password, name='change_password'),
    url(r'^register/$', view=views.register, name='register'),
    url(r'^logout/$', view=views.logout, name='logout'),  # 退出
    url(r'^img_download/', view=views.img_download, name='img_download'),  # 下载图片
    url(r'^get_whether/', view=views.get_whether, name='get_whether'),  # 下载图片

    url(r'^base/', include("base.urls")),
    url(r'^api/', include('guest.urls')),  # api
    url(r'^mocks/', include('mocks.urls')),  # api

    url(r'^favicon.ico$', RedirectView.as_view(url=r'/static/img/E_fa.png')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler400 = views.bad_request
handler403 = views.permission_denied
handler404 = views.page_not_found
handler500 = views.server_error

base/urls.py
# !/usr/bin/env python
# coding=utf-8
# from django.conf import settings
from django.conf.urls import url
from django.urls import path
# from django.conf.urls.static import static
# from django.views.generic.base import RedirectView
from . import views

app_name = "base"
urlpatterns = [
    # 项目
    url(r'project/', view=views.ProjectIndex.as_view(), name='project'),
    url(r'project_add/', view=views.project_add, name='project_add'),
    url(r'project_update/', view=views.project_update, name='project_update'),
    url(r'project_delete/', view=views.project_delete, name='project_delete'),
    # 签名
    url(r'sign/', view=views.SignIndex.as_view(), name='sign'),
    url(r'sign_add/', view=views.sign_add, name='sign_add'),
    url(r'sign_update/', view=views.sign_update, name='sign_update'),
    url(r'sign_delete/', view=views.sign_delete, name='sign_delete'),
    # 测试环境
    url(r'env/', view=views.EnvIndex.as_view(), name='env'),
    url(r'env_add/', view=views.env_add, name='env_add'),
    url(r'env_update/', view=views.env_update, name='env_update'),
    url(r'env_delete/', view=views.env_delete, name='env_delete'),
    url(r'set_headers/', view=views.set_headers, name='set_headers'),
    # 接口
    url(r'interface/', view=views.InterfaceIndex.as_view(), name='interface'),
    url(r'interface_add/', view=views.interface_add, name='interface_add'),
    url(r'interface_update/', view=views.interface_update, name='interface_update'),
    url(r'interface_delete/', view=views.interface_delete, name='interface_delete'),
    url(r'interface_search/', view=views.interface_search, name='interface_search'),
    url(r'interface_copy/', view=views.interface_copy, name='interface_copy'),
    url(r'set_mock/', view=views.set_mock, name='set_mock'),
    # 用例
    url(r'case/', view=views.CaseIndex.as_view(), name='case'),
    url(r'case_add/', view=views.case_add, name='case_add'),
    url(r'case_update/', view=views.case_update, name='case_update'),
    url(r'case_delete/', view=views.case_delete, name='case_delete'),
    url(r'case_run/', view=views.case_run, name='case_run'),
    url(r'case_logs/', view=views.case_logs, name='case_logs'),
    url(r'case_copy/', view=views.case_copy, name='case_copy'),
    url(r'case_search/', view=views.case_search, name='case_search'),
    # 测试计划
    url(r'plan/', view=views.PlanIndex.as_view(), name='plan'),
    url(r'plan_add/', view=views.plan_add, name='plan_add'),
    url(r'plan_update/', view=views.plan_update, name='plan_update'),
    url(r'plan_delete/', view=views.plan_delete, name='plan_delete'),
    url(r'plan_run/', view=views.plan_run, name='plan_run'),
    # 报告
    url(r'^report/', view=views.report_index, name='report'),
    url(r'report_search/', view=views.report_search, name='report_search'),
    # 异步请求获取数据
    url(r'findata/', view=views.findata, name='findata'),
    # 批量导入
    url(r'batch_index', view=views.batch_index, name='batch_index'),
    # 定时任务
    url(r'task/', view=views.TaskIndex.as_view(), name='task'),
    url(r'task_run/', view=views.task_run, name='task_run'),
    url(r'task_logs/', view=views.task_logs, name='task_logs'),
    url(r'task_add/', view=views.task_add, name='task_add'),
    url(r'task_update/', view=views.task_update, name='task_update'),
    url(r'task_delete/', view=views.task_delete, name='task_delete'),
    # 报告页面展示
    url(r'report_page/', view=views.ReportPage.as_view(), name='report_page'),
    url(r'report_logs/', view=views.report_logs, name='report_logs'),  # 日志
    url(r'report_delete/', view=views.report_delete, name='report_delete'),
    url(r'report_results/', view=views.report_results, name='report_results'),  # 获取报告执行结果
    # locust
    url(r'performance/', view=views.performance_index, name='performance'),
    url(r'start_locust/', view=views.start_locust, name='start_locust'),
    url(r'performance_report/', view=views.performance_report, name='performance_report'),
    url(r'performance_real/', view=views.performance_real, name='performance_real'),
    url(r'performance_history/', view=views.performance_history, name='performance_history'),
    url(r'performance_delete/', view=views.performance_delete, name='performance_delete'),
    url(r'performance_status/', view=views.performance_status, name='performance_status'),
    # 下载
    url(r'file_download/', view=views.file_download, name='file_download'),
    # 添加用户
    url(r'user/', view=views.UserIndex.as_view(), name='user'),
    url(r'user_power/', view=views.user_power, name='user_power'),
    # 关于我们
    url(r'about/', view=views.about_index, name='about'),
    url(r'document/', view=views.document, name='document'),
    url(r'debugtalk/', view=views.debugtalk, name='debugtalk'),
    url(r'love/', view=views.love, name='love'),
]

guest/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2019/7/23 16:09
# @Author  : lixiaofeng
# @Site    : 
# @File    : urls.py
# @Software: PyCharm

# coding=utf-8
from django.conf.urls import url
from . import views_api, views_api_sec, views

app_name = "guest"
urlpatterns = [
    # web
    url(r'^index_guest/$', view=views.index, name='index_guest'),  # 登录页面
    url(r'^login_action_guest/$', view=views.login_action, name='login_action_guest'),  # 登录出错跳转
    url(r'^event_manage/$', view=views.event_manage, name='event_manage'),  # 发布会管理
    url(r'^accounts/login/$', view=views.index),  # 验证用户是否登录，未登录跳转到登录页
    url(r'^search_name/$', view=views.search_name, name='search_name'),  # 发布会搜索
    url(r'^guest_manage/$', view=views.guest_manage, name='guest_manage'),  # 嘉宾管理
    url(r'^search_guest/$', view=views.search_guest, name='search_guest'),  # 嘉宾搜索
    url(r'^sign_index/(?P<eid>\d+)/$', view=views.sign_index, name='sign_index'),  # 签到 eid 作为参数传给视图
    url(r'^sign_index_action/(?P<eid>\d+)/$', view=views.sign_index_action, name='sign_index_action'),  # 处理签到操作
    url(r'^logout_guest/$', view=views.logout, name='logout_guest'),  # 退出
    url(r'^delete_all/$', view=views.delete_all, name='delete_all'),  # 清空数据

    # api
    url(r'^add_event/$', view=views_api.add_event, name='add_event'),  # 添加发布会接口
    url(r'^update_event/$', view=views_api.update_event, name='update_event'),  # 修改发布会接口
    url(r'^get_event_list/$', view=views_api.get_event_list, name='get_event_list'),  # 查询发布会接口
    url(r'^add_guest/$', view=views_api.add_guest, name='add_guest'),  # 添加嘉宾接口
    url(r'^get_guest_list/$', view=views_api.get_guest_list, name='get_guest_list'),  # 查询嘉宾接口
    url(r'^user_sign/$', view=views_api.user_sign, name='user_sign'),  # 嘉宾签到接口
    url(r'^login/$', view=views_api.login, name='login'),  # 嘉宾签到接口

    # 加密api
    url(r'^sec_add_event/', view=views_api_sec.sec_add_event, name='sec_add_event'),  # 添加发布会加密接口
    url(r'^sec_get_event_list/', view=views_api_sec.sec_get_event_list, name='sec_get_event_list'),  # 查询发布会加密接口
    url(r'^sec_get_guest_list/', view=views_api_sec.sec_get_guest_list, name='sec_get_guest_list'),  # 查询嘉宾接口

]

templates/sign/event_manage.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'img/favicon.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'img/favicon.png' %}">
    <!-- 加载bootstrap3的应用、CSS。JavaScript文件-->
    {% load bootstrap3 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <title>发布会管理</title>
</head>
<body role="document">
<!-- 导航栏 -->
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'guest:event_manage' %}">嘉宾管理系统</a>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <!--class="active"表示当前菜单处于选中状态 -->
                <li class="active"><a href="#">发布会</a></li>
                <li><a href="{% url 'guest:guest_manage' %}">嘉宾</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">{{ user }}</a></li>
                {#                <li><a href="/api/logout_guest/">退出</a></li>#}
                <li><a href="{% url 'index' %}">返回测试平台</a></li>
                <li><a href="{% url 'guest:delete_all' %}">清空数据</a></li>
            </ul>
        </div>
    </div>
</nav>
<!-- 发布会搜索表单-->
<div class="page-header" style="padding-top: 60px;">
    <div id="navbar" class="navbar-collapse collapse">
        <form class="navbar-form" method="get" action="{% url 'guest:search_name' %}">
            <div class="form-group">
                <input name="name" type="text" placeholder="名称" class="form-control">
            </div>
            <button type="submit" class="btn btn-success">搜索</button>
        </form>
    </div>
</div>
<!-- 发布会列表 -->
<div class="row" style="padding-top: 10px;">
    <div class="col-md-6">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>id</th>
                <th>发布会名称</th>
                <th>状态</th>
                <th>地址</th>
                <th>时间</th>
                <th>签到</th>
            </tr>
            </thead>
            <tbody>
            {% for event in events %}
                <tr>
                    <td>{{ event.id }}</td>
                    <td>{{ event.name }}</td>
                    <td>{{ event.status }}</td>
                    <td>{{ event.address }}</td>
                    <td>{{ event.start_time }}</td>
                    <!--target=" xxx _blank" 设置属性在新窗口打开-->
                    <td><a href="/api/sign_index/{{ event.id }}">sign</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<!--列表分页 搜索列表分页-->
<div class="pagination" style="padding-left: 5%">
    <span class="step-links">
        {% if events.has_previous %}
            {% if search_name %}
                <a href="?name={{ search_name }}&&page={{ events.previous_page_number }}">上一页</a>
            {% else %}
                <a href="?page={{ events.previous_page_number }}">上一页</a>
            {% endif %}
        {% endif %}
        {% for index in events.paginator.page_range %}
            {% if data.number == index %}
                <span class="current">{{ index }}</span>
            {% else %}
                {% if search_name %}
                    <span class="current"><a href="?name={{ search_name }}&&page={{ index }}">{{ index }}</a></span>
                {% else %}
                    <span class="current"><a href="?page={{ index }}">{{ index }}</a></span>
                {% endif %}
            {% endif %}
        {% endfor %}
        {% if events.has_next %}
            {% if search_name %}
                <a href="?name={{ search_name }}&&page={{ events.next_page_number }}">下一页</a>
            {% else %}
                <a href="?page={{ events.next_page_number }}">下一页</a>
            {% endif %}
        {% endif %}
    </span>
</div>
</body>
</html>

templates/sign/guest_manage.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'img/favicon.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'img/favicon.png' %}">
    <!-- 加载bootstrap3的应用、CSS。JavaScript文件-->
    {% load bootstrap3 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <title>嘉宾管理</title>
</head>
<body role="document">
<!-- 导航栏 -->
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'guest:guest_manage' %}">嘉宾管理系统</a>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <!--class="active"表示当前菜单处于选中状态 -->
                <li><a href="{% url 'guest:event_manage' %}">发布会</a></li>
                <li class="active"><a href="#">嘉宾</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">{{ user }}</a></li>
{#                <li><a href="/api/logout_guest/">退出</a></li>#}
                <li><a href="{% url 'index' %}">返回测试平台</a></li>
                <li><a href="{% url 'guest:delete_all' %}">清空数据</a></li>
            </ul>
        </div>
    </div>
</nav>
<!-- 嘉宾搜索表单-->
<div class="page-header" style="padding-top: 60px;">
    <div id="navbar" class="navbar-collapse collapse">
        <form class="navbar-form" method="get" action="{% url 'guest:search_guest' %}">
            <div class="form-group">
                <input name="name" type="text" placeholder="姓名、手机号或发布会名称" class="form-control">
            </div>
            <button type="submit" class="btn btn-success">搜索</button>
        </form>
    </div>
</div>
<!-- 嘉宾列表 -->
<div class="row" style="padding-top: 10px;">
    <div class="col-md-6">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>id</th>
                <th>名称</th>
                <th>手机</th>
                <th>Email</th>
                <th>签到</th>
                <th>发布会</th>
            </tr>
            </thead>
            <tbody>
            {% for guest in guests %}
                <tr>
                    <td>{{ guest.id }}</td>
                    <td>{{ guest.realname }}</td>
                    <td>{{ guest.phone }}</td>
                    <td>{{ guest.email }}</td>
                    <td>{{ guest.sign }}</td>
                    <td>{{ guest.event }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<!--列表分页 列表分页 搜索列表分页-->
<div class="pagination" style="padding-left: 5%">
    <span class="step-links">
        {% if guests.has_previous %}
            {% if search_guest %}
                <a href="?name={{ search_guest }}&&page={{ guests.previous_page_number }}">上一页</a>
            {% else %}
                <a href="?page={{ guests.previous_page_number }}">上一页</a>
            {% endif %}
        {% endif %}
        {% for index in guests.paginator.page_range %}
            {% if data.number == index %}
                <span class="current">{{ index }}</span>
            {% else %}
                {% if search_guest %}
                    <span class="current"><a href="?name={{ search_guest }}&&page={{ index }}">{{ index }}</a></span>
                {% else %}
                    <span class="current"><a href="?page={{ index }}">{{ index }}</a></span>
                {% endif %}
            {% endif %}
        {% endfor %}
        {% if guests.has_next %}
            {% if search_guest %}
                <a href="?name={{ search_guest }}&&page={{ guests.next_page_number }}">下一页</a>
            {% else %}
                <a href="?page={{ guests.next_page_number }}">下一页</a>
            {% endif %}
        {% endif %}
    </span>
</div>
</body>
</html>

templates/sign/login.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'img/favicon.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'img/favicon.png' %}">
    <!-- 加载bootstrap3的应用、CSS。JavaScript文件-->
    {% load bootstrap3 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <title>登录</title>
</head>
<body>
<!-- 导航栏 -->
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">返回测试平台</a>
    </div>
</nav>
<div class="page-header" style="padding-top: 80px;margin-left: 20%">

    <form class="navbar-form" method="post" action="{% url 'guest:login_action_guest' %}">
        {% csrf_token %}
        <div id="navbar" class="navbar-collapse collapse">
            <div class="ui-spinner-input">
                <span>账户：</span>
                <input name="username" type="text" placeholder="username" class="form-control" required="required">
            </div>
            <br>
            <div class="ui-spinner-input">
                <span>密码：</span>
                <input name="password" type="password" placeholder="password" class="form-control" required="required">
            </div>
            <p class="errors" style="color: red"> {{ error }} </p>
            <button type="submit" class="btn btn-success">登录</button>
        </div>
    </form>
</div>
</body>
</html>

templates/sign/sign_index.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'img/favicon.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'img/favicon.png' %}">
    <!-- 加载bootstrap3的应用、CSS。JavaScript文件-->
    {% load bootstrap3 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <title>签到</title>
</head>
<body role="document">
<!-- 导航栏 -->
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <!--标题设置为发布会名称-->
            <a class="navbar-brand" href="#">{{ event.name }}</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <!--class="active"表示当前菜单处于选中状态 -->
                <li><a href="{% url 'guest:event_manage' %}">发布会</a></li>
                <li><a href="{% url 'guest:guest_manage' %}">嘉宾</a></li>
                <li><a href="{% url 'index' %}">返回测试平台</a></li>
            </ul>
        </div>
    </div>
</nav>
<!--签到功能-->
<div class="page-header" style="padding-top: 80px;">
    <div id="navbar" class="navbar-collapse collapse">
        <form class="navbar-form" method="post" action="/api/sign_index_action/{{ event.id }}/">
            {% csrf_token %}
            <div class="form-group">
                <input name="phone" type="text" placeholder="输入手机号" class="form-control">
            </div>
            <button type="submit" class="btn btn-success">签到</button>
            <!-- hint 显示签到成功和失败的提示信息-->
            <font color="red">
                <br>{{ hint }}
                <br>{{ guest.realname }}
                <br>{{ guest.phone }}
            </font>
        </form>
    </div>
</div>
</body>
</html>