EasyTest/urls.py
from django.contrib import admin
# from django.urls import path
from django.conf.urls import include
# from EasyTest.views import index
from EasyTest import views
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

admin.site.site_header = 'EasyTest-后台管理'
admin.site.site_title = 'EasyTest-Manage'

urlpatterns = [

    url(r'admin/', admin.site.urls),
    url(r'^$', view=views.index, name="index"),
    url(r'index/$', view=views.index, name="index"),
    url(r'index_data/$', view=views.index_data, name="index_data"),
    url(r'^login_action/$', view=views.login_action, name='login_action'),
    url(r'^change_password/$', view=views.change_password, name='change_password'),
    url(r'^register/$', view=views.register, name='register'),
    url(r'^logout/$', view=views.logout, name='logout'),  # 退出
    url(r'^img_download/', view=views.img_download, name='img_download'),  # 下载图片
    url(r'^get_whether/', view=views.get_whether, name='get_whether'),  # 下载图片

    url(r'^base/', include("base.urls")),
    url(r'^api/', include('guest.urls')),  # api
    url(r'^mocks/', include('mocks.urls')),  # api

    url(r'^favicon.ico$', RedirectView.as_view(url=r'/static/img/E_fa.png')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler400 = views.bad_request
handler403 = views.permission_denied
handler404 = views.page_not_found
handler500 = views.server_error

base/urls.py
# !/usr/bin/env python
# coding=utf-8
# from django.conf import settings
from django.conf.urls import url
from django.urls import path
# from django.conf.urls.static import static
# from django.views.generic.base import RedirectView
from . import views

app_name = "base"
urlpatterns = [
    # 项目
    url(r'project/', view=views.ProjectIndex.as_view(), name='project'),
    url(r'project_add/', view=views.project_add, name='project_add'),
    url(r'project_update/', view=views.project_update, name='project_update'),
    url(r'project_delete/', view=views.project_delete, name='project_delete'),
    # 签名
    url(r'sign/', view=views.SignIndex.as_view(), name='sign'),
    url(r'sign_add/', view=views.sign_add, name='sign_add'),
    url(r'sign_update/', view=views.sign_update, name='sign_update'),
    url(r'sign_delete/', view=views.sign_delete, name='sign_delete'),
    # 测试环境
    url(r'env/', view=views.EnvIndex.as_view(), name='env'),
    url(r'env_add/', view=views.env_add, name='env_add'),
    url(r'env_update/', view=views.env_update, name='env_update'),
    url(r'env_delete/', view=views.env_delete, name='env_delete'),
    url(r'set_headers/', view=views.set_headers, name='set_headers'),
    # 接口
    url(r'interface/', view=views.InterfaceIndex.as_view(), name='interface'),
    url(r'interface_add/', view=views.interface_add, name='interface_add'),
    url(r'interface_update/', view=views.interface_update, name='interface_update'),
    url(r'interface_delete/', view=views.interface_delete, name='interface_delete'),
    url(r'interface_search/', view=views.interface_search, name='interface_search'),
    url(r'interface_copy/', view=views.interface_copy, name='interface_copy'),
    url(r'set_mock/', view=views.set_mock, name='set_mock'),
    # 用例
    url(r'case/', view=views.CaseIndex.as_view(), name='case'),
    url(r'case_add/', view=views.case_add, name='case_add'),
    url(r'case_update/', view=views.case_update, name='case_update'),
    url(r'case_delete/', view=views.case_delete, name='case_delete'),
    url(r'case_run/', view=views.case_run, name='case_run'),
    url(r'case_logs/', view=views.case_logs, name='case_logs'),
    url(r'case_copy/', view=views.case_copy, name='case_copy'),
    url(r'case_search/', view=views.case_search, name='case_search'),
    # 测试计划
    url(r'plan/', view=views.PlanIndex.as_view(), name='plan'),
    url(r'plan_add/', view=views.plan_add, name='plan_add'),
    url(r'plan_update/', view=views.plan_update, name='plan_update'),
    url(r'plan_delete/', view=views.plan_delete, name='plan_delete'),
    url(r'plan_run/', view=views.plan_run, name='plan_run'),
    # 报告
    url(r'^report/', view=views.report_index, name='report'),
    url(r'report_search/', view=views.report_search, name='report_search'),
    # 异步请求获取数据
    url(r'findata/', view=views.findata, name='findata'),
    # 批量导入
    url(r'batch_index', view=views.batch_index, name='batch_index'),
    # 定时任务
    url(r'task/', view=views.TaskIndex.as_view(), name='task'),
    url(r'task_run/', view=views.task_run, name='task_run'),
    url(r'task_logs/', view=views.task_logs, name='task_logs'),
    url(r'task_add/', view=views.task_add, name='task_add'),
    url(r'task_update/', view=views.task_update, name='task_update'),
    url(r'task_delete/', view=views.task_delete, name='task_delete'),
    # 报告页面展示
    url(r'report_page/', view=views.ReportPage.as_view(), name='report_page'),
    url(r'report_logs/', view=views.report_logs, name='report_logs'),  # 日志
    url(r'report_delete/', view=views.report_delete, name='report_delete'),
    url(r'report_results/', view=views.report_results, name='report_results'),  # 获取报告执行结果
    # locust
    url(r'performance/', view=views.performance_index, name='performance'),
    url(r'start_locust/', view=views.start_locust, name='start_locust'),
    url(r'performance_report/', view=views.performance_report, name='performance_report'),
    url(r'performance_real/', view=views.performance_real, name='performance_real'),
    url(r'performance_history/', view=views.performance_history, name='performance_history'),
    url(r'performance_delete/', view=views.performance_delete, name='performance_delete'),
    url(r'performance_status/', view=views.performance_status, name='performance_status'),
    # 下载
    url(r'file_download/', view=views.file_download, name='file_download'),
    # 添加用户
    url(r'user/', view=views.UserIndex.as_view(), name='user'),
    url(r'user_power/', view=views.user_power, name='user_power'),
    # 关于我们
    url(r'about/', view=views.about_index, name='about'),
    url(r'document/', view=views.document, name='document'),
    url(r'debugtalk/', view=views.debugtalk, name='debugtalk'),
    url(r'love/', view=views.love, name='love'),
]

templates/system/task/log.html
{% extends "base.html" %}

{% block css %}
    <style>
        #plan_name {
            color: #000000;
            font-weight: 900;
        }

        #if_name {
            color: #555;
            font-weight: 700;
        }

        #case_name {
            color: #333;
            font-weight: 800;
        }

        p {
            color: #666;
            font-family: "Bitstream Vera Sans Mono", Monaco, "Courier New", Courier, monospace;
        }

        #make {
            font-weight: 200;
            font-size: 8px;
            margin-left: 3%;
        }

        #make span {
            color: red;
        }

        #error_log {
            color: #FF3333;
        }

        /*返回顶部样式*/
        #myBtn {
            display: none;
            position: fixed;
            bottom: 20px;
            right: 30px;
            z-index: 99;
            border: none;
            outline: none;
            background-color: #999c9e;
            color: white;
            cursor: pointer;
            padding: 15px;
            border-radius: 10px;
        }

        #myBtn:hover {
            background-color: #555;
        }

        a:hover {
            color: red;
        }

        .btn-primary:hover {
            color: red;
        }
    </style>

{% endblock %}

{% block nav %}
    {% for object in model_list %}
        <li><a href="{{ object.url }}"><i class="{{ object.icon }}"></i>{{ object.model_name }}</a>
        </li>

    {% endfor %}

{% endblock %}


{% block crumbs %}
    <div class="row">
        <div class="col-md-12">
            <ol class="breadcrumb">
                <li class="active">
                    <a class="this-page" href="{% url 'base:task' %}">定时任务</a>
                </li>
                <li class="active">
                    <a class="this">运行日志</a>
                </li>
            </ol>
        </div>
    </div>
{% endblock %}

{% block body %}
    <div class="row">
    <div class="col-md-12">
        <div class="panel">
            {% if unicode %}
                <div id="log" style="margin: 1% 1%">
                    <script type="text/javascript">
                        alert("没有发现该日志文件！！！");
                    </script>
                </div>
            {% else %}
                <div style="margin: 1% 1%">
                    {% if log_file %}
                        <a href="{% url 'base:file_download' %}?log_file={{ log_file }}" class="btn btn-primary"><i
                                class="fa fa-cloud-download"></i>&nbsp;下载运行任务日志</a>
                        <button onclick="get_task_log()" class="btn btn-primary"><i
                                class="fa fa-code-fork"></i>&nbsp;格式化日志
                        </button>
                    {% endif %}
                </div>
                <div class="spinner"></div>
                {% if make %}

                    <div id="log" style="margin: 1% 1%">
                        {% ifequal data '0' %}
                            <p style="color: red">没有权限！请联系管理员获取.</p>
                        {% else %}
                            {% for foo in data %}
                                {{ foo }}<br>
                            {% endfor %}
                        {% endifequal %}
                    </div>
                {% endif %}
            {% endif %}
        </div>
        <button onclick="topFunction()" id="myBtn" title="回顶部">返回顶部</button>
    </div>
{% endblock %}

{% block javascript %}
    <script>
        // 当网页向下滑动 20px 出现"返回顶部" 按钮
        window.onscroll = function () {
            scrollFunction()
        };

        function scrollFunction() {
            if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
                document.getElementById("myBtn").style.display = "block";
            } else {
                document.getElementById("myBtn").style.display = "none";
            }
        }

        // 点击按钮，返回顶部
        function topFunction() {
            document.body.scrollTop = 0;
            document.documentElement.scrollTop = 0;
        }

        // 隐藏log
        function del_log() {
            $('#all_log').empty();
        }

        function get_task_log() {
            $('.spinner').show();
            $('#log').empty();
            $.ajax({
                type: "get",
                url: "/base/findata",
                data: {
                    "type": "get_task_log"
                },
                success: function (data) {
                    {#                    console.log('---------------->', data);#}
                    if (JSON.stringify(data) != '[]') {
                        for (item in data) {
                            $('.spinner').hide();
                            var spl = 'interface response data: ';
                            if (data[item].indexOf(spl) != -1) {
                                var log = data[item].split('interface response data: ')[1];
                                var log_ = data[item].split('interface response data: ')[0];
                                var json = eval("(" + log + ")");

                                $('#log').append("<p>" + "<span>" + log_ + "</span>" + "<span id='case_name'>" + json.case_name + "</span></p>");
                                for (i in json.step_list) {
                                    l = json.step_list[i];
                                    $('#log').append("<p>" + "<span>" + log_ + "</span>" + "<span id='if_name'>" + l.if_name + "</span></p>");
                                    $('#log').append("<p>" + log_ + '请求url' + ':' + l.url + '    ' + '请求方式' + ':' + l.method + "</p>");
                                    $('#log').append("<p>" + log_ + '数据类型' + ':' + l.data_type + "</p>");
                                    $('#log').append("<p>" + log_ + 'headers' + ':' + JSON.stringify(l.header) + "</p>");
                                    $('#log').append("<p>" + log_ + '请求body' + ':' + JSON.stringify(l.body) + "</p>");
                                    $('#log').append("<p>" + log_ + '页面返回信息' + ':' + JSON.stringify(l.res_content) + "</p>");
                                    {#                                    $('#all_log').append("<p>" + log_ + '检查点' + ':' + l.check_filed + '  ' + l.expect_filed + "</p>");#}
                                    $('#log').append("<p>" + log_ + '检查点' + ':' + l.checkpoint + "</p>");
                                    $('#log').append("<p>" + log_ + '测试结果' + ':' + l.result + '    ' + 'msg' + ':' + l.msg + "</p></br>");
                                }
                            } else {
                                // 显示错误日志
                                if (data[item].indexOf('[20') == -1) {
                                    $('#log').append("<p id='error_log'>" + data[item] + "</p>");
                                } else {
                                    $('#log').append("<br>");
                                    $('#log').append("<p>" + data[item] + "</p><br>");
                                }
                            }
                        }

                    }
                    else {
                        alert('没有发现日志！')
                    }
                },
                error: function () {
                    alert("error");
                }
            });

        }

    </script>
{% endblock %}

templates/system/task/task_index.html
{% extends "base.html" %}

{% block css %}
    <style>
        #cen {
            text-align: center;
        }

        a:hover {
            color: red;
        }

        .btn-primary:hover {
            color: red;
        }

        tr:hover {
            background-color: #e7e7e7;
        }
    </style>
{% endblock %}

{% block nav %}
    {% for foo in model_list %}
        <li><a href="{{ foo.url }}"><i class="{{ foo.icon }}"></i>{{ foo.model_name }}</a>
        </li>
    {% endfor %}

{% endblock %}

{% block crumbs %}
    <div class="row">
        <div class="col-md-12">
            <ol class="breadcrumb">
                <li class="active">
                    <a class="this-page">定时任务</a>
                </li>
            </ol>

        </div>
    </div>
{% endblock %}

{% block body %}

    <div class="row">
        <div class="col-md-12">
            <div class="panel">
                <div class="panel-heading">
                    <a class="btn btn-primary" id="add_id_PeriodicTask"
                       href="{% url 'base:task_add' %}" title="增加另一个 测试用例">
                        <i class="fa fa-plus-circle"></i>&nbsp;添加任务
                    </a>&nbsp;&nbsp;&nbsp;
                    <a class="btn btn-primary" id="add_id_PeriodicTask"
                       href="http://www.easytest.xyz:5555" title="" target="_blank"><i class="fa fa-bullseye"></i>&nbsp;任务监控
                    </a>&nbsp;&nbsp;&nbsp;
                    <a href="{% url 'base:task_logs' %}" class="btn btn-primary"><i class="fa fa-file-text-o"></i>&nbsp;任务运行日志</a>
                </div>
                <div class="panel-body">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th id="cen">ID</th>
                            <th id="cen">任务名称</th>
                            <th id="cen">任务模块</th>
                            <th id="cen">执行时间</th>
                            <th id="cen">执行计划</th>
                            <th id="cen">更新时间</th>
                            <th id="cen">状态</th>
                            <th id="cen">操作</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for task in object_list %}
                            <tr>

                                <td id="cen" class="task_id">{{ task.id }}</td>
                                <td><a class="related-widget-wrapper-link add-related"
                                       id="add_id_Apitest"
                                       href="{% url 'base:task_update' %}?task_id={{ task.id }}&&page={{ page }}">{{ task.name }}</a>
                                </td>
                                <td>{{ task.task }}</td>
                                {% if task.crontab %}
                                    <td>
                                        <span style='color:green'>{{ task.crontab.minute }} {{ task.crontab.hour }} {{ task.crontab.day_of_week }} {{ task.crontab.day_of_month }} {{ task.crontab.month_of_year }}
                                            (m/h/d/dM/MY)</span></td>
                                {% else %}
                                    {% if task.interval %}
                                        <td>
                                            <span style='color:green'>{{ task.interval.every }} {{ task.interval.period }}/次</span>
                                        </td>
                                    {% endif %}
                                {% endif %}
                                <td id="cen">{{ task.args }}</td>
                                <td id="cen">{{ task.date_changed }}</td>
                                <td id="cen">{{ task.enabled }}</td>
                                <td id="cen">
                                    <a href="#" onclick="run_delay(this)"
                                       class="layui-btn layui-btn-danger layui-btn-xs"
                                       data-toggle="modal" data-target="#runCaseForm"><i
                                            class="fa fa-recycle"></i>&nbsp;&nbsp;&nbsp;
                                    </a>
                                    <a href="{% url 'base:task_delete' %}?task_id={{ task.id }}&&page={{ page }}"
                                       onclick="return delete_btn()"
                                       class="layui-btn layui-btn-danger layui-btn-xs"><img
                                            src="/static/admin/img/icon-deletelink.svg"/>&nbsp;&nbsp;&nbsp;</a>
                                </td>

                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    {% if error %}
                        <span style="color: red; font-size: 10px;">{{ error }}</span>
                    {% endif %}

                </div>
                {% if is_paginated %}
                    <ul class="pagination">
                        {% if first %}
                            <li class="page"><a href="?page=1">1</a></li>
                        {% endif %}
                        {% if left %}
                            {% if left_has_more %}
                                <li class="page"><a href="javascript:void(0)">...</a></li>
                            {% endif %}
                            {% for i in left %}
                                <li class="page"><a href="?page={{ i }}">{{ i }}</a></li>
                            {% endfor %}
                        {% endif %}
                        <li class="page"><a href="javascript:void(0)" class="active"> {{ page_obj.number }}</a></li>
                        {% if right %}
                            {% for i in right %}
                                <li class="page"><a href="?page={{ i }}">{{ i }}</a></li>
                            {% endfor %}
                            {% if right_has_more %}
                                <li class="page"><a href="javascript:void(0)">...</a></li>
                            {% endif %}
                        {% endif %}
                        {% if last %}
                            <li class="page"><a
                                    href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>
                            </li>
                        {% endif %}

                    </ul>
                {% endif %}
            </div>

        </div>
    </div>


{% endblock %}

{% block javascript %}
    <script>

        //删除
        function delete_btn() {
            if (window.confirm("你确定要删除吗？")) {
                return true;//确定返回真
            }
            else {
                return false;//取消返回假
            }
        }

        function run_delay(obj) {
            var task_id = obj.parentNode.parentNode.children[0].innerText;
            $.ajax({
                type: "post",
                url: "/base/task_run/",
                data: {"id": task_id},
                success: function (data) {
                    if (confirm(data)) {
                        location = "/base/report_page/"
                    } else {

                    }

                },
                error: function () {
                    alert("执行失败");
                    $('.spinner').hide();
                }
            });

        }


    </script>
{% endblock %}