EasyTest/urls.py
from django.contrib import admin
# from django.urls import path
from django.conf.urls import include
# from EasyTest.views import index
from EasyTest import views
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

admin.site.site_header = 'EasyTest-后台管理'
admin.site.site_title = 'EasyTest-Manage'

urlpatterns = [

    url(r'admin/', admin.site.urls),
    url(r'^$', view=views.index, name="index"),
    url(r'index/$', view=views.index, name="index"),
    url(r'index_data/$', view=views.index_data, name="index_data"),
    url(r'^login_action/$', view=views.login_action, name='login_action'),
    url(r'^change_password/$', view=views.change_password, name='change_password'),
    url(r'^register/$', view=views.register, name='register'),
    url(r'^logout/$', view=views.logout, name='logout'),  # 退出
    url(r'^img_download/', view=views.img_download, name='img_download'),  # 下载图片
    url(r'^get_whether/', view=views.get_whether, name='get_whether'),  # 下载图片

    url(r'^base/', include("base.urls")),
    url(r'^api/', include('guest.urls')),  # api
    url(r'^mocks/', include('mocks.urls')),  # api

    url(r'^favicon.ico$', RedirectView.as_view(url=r'/static/img/E_fa.png')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler400 = views.bad_request
handler403 = views.permission_denied
handler404 = views.page_not_found
handler500 = views.server_error

base/urls.py
# !/usr/bin/env python
# coding=utf-8
# from django.conf import settings
from django.conf.urls import url
from django.urls import path
# from django.conf.urls.static import static
# from django.views.generic.base import RedirectView
from . import views

app_name = "base"
urlpatterns = [
    # 项目
    url(r'project/', view=views.ProjectIndex.as_view(), name='project'),
    url(r'project_add/', view=views.project_add, name='project_add'),
    url(r'project_update/', view=views.project_update, name='project_update'),
    url(r'project_delete/', view=views.project_delete, name='project_delete'),
    # 签名
    url(r'sign/', view=views.SignIndex.as_view(), name='sign'),
    url(r'sign_add/', view=views.sign_add, name='sign_add'),
    url(r'sign_update/', view=views.sign_update, name='sign_update'),
    url(r'sign_delete/', view=views.sign_delete, name='sign_delete'),
    # 测试环境
    url(r'env/', view=views.EnvIndex.as_view(), name='env'),
    url(r'env_add/', view=views.env_add, name='env_add'),
    url(r'env_update/', view=views.env_update, name='env_update'),
    url(r'env_delete/', view=views.env_delete, name='env_delete'),
    url(r'set_headers/', view=views.set_headers, name='set_headers'),
    # 接口
    url(r'interface/', view=views.InterfaceIndex.as_view(), name='interface'),
    url(r'interface_add/', view=views.interface_add, name='interface_add'),
    url(r'interface_update/', view=views.interface_update, name='interface_update'),
    url(r'interface_delete/', view=views.interface_delete, name='interface_delete'),
    url(r'interface_search/', view=views.interface_search, name='interface_search'),
    url(r'interface_copy/', view=views.interface_copy, name='interface_copy'),
    url(r'set_mock/', view=views.set_mock, name='set_mock'),
    # 用例
    url(r'case/', view=views.CaseIndex.as_view(), name='case'),
    url(r'case_add/', view=views.case_add, name='case_add'),
    url(r'case_update/', view=views.case_update, name='case_update'),
    url(r'case_delete/', view=views.case_delete, name='case_delete'),
    url(r'case_run/', view=views.case_run, name='case_run'),
    url(r'case_logs/', view=views.case_logs, name='case_logs'),
    url(r'case_copy/', view=views.case_copy, name='case_copy'),
    url(r'case_search/', view=views.case_search, name='case_search'),
    # 测试计划
    url(r'plan/', view=views.PlanIndex.as_view(), name='plan'),
    url(r'plan_add/', view=views.plan_add, name='plan_add'),
    url(r'plan_update/', view=views.plan_update, name='plan_update'),
    url(r'plan_delete/', view=views.plan_delete, name='plan_delete'),
    url(r'plan_run/', view=views.plan_run, name='plan_run'),
    # 报告
    url(r'^report/', view=views.report_index, name='report'),
    url(r'report_search/', view=views.report_search, name='report_search'),
    # 异步请求获取数据
    url(r'findata/', view=views.findata, name='findata'),
    # 批量导入
    url(r'batch_index', view=views.batch_index, name='batch_index'),
    # 定时任务
    url(r'task/', view=views.TaskIndex.as_view(), name='task'),
    url(r'task_run/', view=views.task_run, name='task_run'),
    url(r'task_logs/', view=views.task_logs, name='task_logs'),
    url(r'task_add/', view=views.task_add, name='task_add'),
    url(r'task_update/', view=views.task_update, name='task_update'),
    url(r'task_delete/', view=views.task_delete, name='task_delete'),
    # 报告页面展示
    url(r'report_page/', view=views.ReportPage.as_view(), name='report_page'),
    url(r'report_logs/', view=views.report_logs, name='report_logs'),  # 日志
    url(r'report_delete/', view=views.report_delete, name='report_delete'),
    url(r'report_results/', view=views.report_results, name='report_results'),  # 获取报告执行结果
    # locust
    url(r'performance/', view=views.performance_index, name='performance'),
    url(r'start_locust/', view=views.start_locust, name='start_locust'),
    url(r'performance_report/', view=views.performance_report, name='performance_report'),
    url(r'performance_real/', view=views.performance_real, name='performance_real'),
    url(r'performance_history/', view=views.performance_history, name='performance_history'),
    url(r'performance_delete/', view=views.performance_delete, name='performance_delete'),
    url(r'performance_status/', view=views.performance_status, name='performance_status'),
    # 下载
    url(r'file_download/', view=views.file_download, name='file_download'),
    # 添加用户
    url(r'user/', view=views.UserIndex.as_view(), name='user'),
    url(r'user_power/', view=views.user_power, name='user_power'),
    # 关于我们
    url(r'about/', view=views.about_index, name='about'),
    url(r'document/', view=views.document, name='document'),
    url(r'debugtalk/', view=views.debugtalk, name='debugtalk'),
    url(r'love/', view=views.love, name='love'),
]

guest/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2019/7/23 16:09
# @Author  : lixiaofeng
# @Site    : 
# @File    : urls.py
# @Software: PyCharm

# coding=utf-8
from django.conf.urls import url
from . import views_api, views_api_sec, views

app_name = "guest"
urlpatterns = [
    # web
    url(r'^index_guest/$', view=views.index, name='index_guest'),  # 登录页面
    url(r'^login_action_guest/$', view=views.login_action, name='login_action_guest'),  # 登录出错跳转
    url(r'^event_manage/$', view=views.event_manage, name='event_manage'),  # 发布会管理
    url(r'^accounts/login/$', view=views.index),  # 验证用户是否登录，未登录跳转到登录页
    url(r'^search_name/$', view=views.search_name, name='search_name'),  # 发布会搜索
    url(r'^guest_manage/$', view=views.guest_manage, name='guest_manage'),  # 嘉宾管理
    url(r'^search_guest/$', view=views.search_guest, name='search_guest'),  # 嘉宾搜索
    url(r'^sign_index/(?P<eid>\d+)/$', view=views.sign_index, name='sign_index'),  # 签到 eid 作为参数传给视图
    url(r'^sign_index_action/(?P<eid>\d+)/$', view=views.sign_index_action, name='sign_index_action'),  # 处理签到操作
    url(r'^logout_guest/$', view=views.logout, name='logout_guest'),  # 退出
    url(r'^delete_all/$', view=views.delete_all, name='delete_all'),  # 清空数据

    # api
    url(r'^add_event/$', view=views_api.add_event, name='add_event'),  # 添加发布会接口
    url(r'^update_event/$', view=views_api.update_event, name='update_event'),  # 修改发布会接口
    url(r'^get_event_list/$', view=views_api.get_event_list, name='get_event_list'),  # 查询发布会接口
    url(r'^add_guest/$', view=views_api.add_guest, name='add_guest'),  # 添加嘉宾接口
    url(r'^get_guest_list/$', view=views_api.get_guest_list, name='get_guest_list'),  # 查询嘉宾接口
    url(r'^user_sign/$', view=views_api.user_sign, name='user_sign'),  # 嘉宾签到接口
    url(r'^login/$', view=views_api.login, name='login'),  # 嘉宾签到接口

    # 加密api
    url(r'^sec_add_event/', view=views_api_sec.sec_add_event, name='sec_add_event'),  # 添加发布会加密接口
    url(r'^sec_get_event_list/', view=views_api_sec.sec_get_event_list, name='sec_get_event_list'),  # 查询发布会加密接口
    url(r'^sec_get_guest_list/', view=views_api_sec.sec_get_guest_list, name='sec_get_guest_list'),  # 查询嘉宾接口

]

mocks/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2019/10/14 17:30
# @Author  : lixiaofeng
# @Site    : 
# @File    : urls.py
# @Software: PyCharm

from django.conf.urls import url
# from django.conf.urls.static import static
# from django.views.generic.base import RedirectView
from . import views

app_name = "mocks"
urlpatterns = [
    # 项目
    url(r'api/?', view=views.mock_api, name='mock_api'),
    url(r'[\w|\/]+', view=views.dispatch_request, name='dispatch_request'),

]

base/models.py
from django.db import models
from django.contrib.auth.models import User
from djcelery.models import PeriodicTask


class Sign(models.Model):
    sign_id = models.AutoField(primary_key=True, null=False)
    sign_name = models.CharField(max_length=100)
    sign_type = models.CharField(max_length=100, default="无")
    description = models.CharField(max_length=200)
    update_time = models.DateTimeField('更新时间', auto_now=True)
    update_user = models.CharField(max_length=30, default='')

    def __str__(self):
        return self.sign_name

    class Meta:
        verbose_name = "签名管理"
        verbose_name_plural = "签名管理"


class Project(models.Model):
    prj_id = models.AutoField(primary_key=True, null=False)
    prj_name = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default='')
    sign = models.ForeignKey(Sign, on_delete=models.CASCADE, default='')
    description = models.CharField(max_length=200)
    update_time = models.DateTimeField('更新时间', auto_now=True)

    def __str__(self):
        return self.prj_name

    class Meta:
        verbose_name = "项目管理"
        verbose_name_plural = "项目管理"


class Environment(models.Model):
    env_id = models.AutoField(primary_key=True, null=False)
    env_name = models.CharField(max_length=100)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    description = models.CharField(max_length=200)
    url = models.CharField(max_length=100)
    import_url = models.CharField(max_length=100,default="")
    is_swagger = models.IntegerField(default=0)  # 导入swagger
    set_headers = models.TextField(default='')  # 设置默认headers
    private_key = models.CharField(max_length=100)
    update_time = models.DateTimeField('更新时间', auto_now=True)
    update_user = models.CharField(max_length=30, default='')

    def __str__(self):
        return self.env_name

    class Meta:
        verbose_name = "测试环境"
        verbose_name_plural = "测试环境"


class Interface(models.Model):
    if_id = models.AutoField(primary_key=True, null=False)
    if_name = models.CharField(max_length=100)
    url = models.CharField(max_length=100)
    method = models.CharField(max_length=10)
    data_type = models.CharField(max_length=10)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    is_sign = models.IntegerField()
    is_header = models.IntegerField(default=0)  # 标记设置header接口
    set_mock = models.TextField(default='')  # 设置mock
    skip = models.TextField(default='')  # 跳过
    description = models.CharField(max_length=200)
    request_header_param = models.TextField()
    request_body_param = models.TextField()
    response_header_param = models.TextField()
    response_body_param = models.TextField()
    update_time = models.DateTimeField('更新时间', auto_now=True)
    update_user = models.CharField(max_length=30, default='')

    def __str__(self):
        return self.if_name

    class Meta:
        verbose_name = "接口管理"
        verbose_name_plural = "接口管理"


class Case(models.Model):
    case_id = models.AutoField(primary_key=True, null=False)
    case_name = models.CharField(max_length=100)
    weight = models.IntegerField(default=1)  # 权重
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    description = models.CharField(max_length=200)
    content = models.TextField()
    update_time = models.DateTimeField('更新时间', auto_now=True)
    update_user = models.CharField(max_length=30, default='')

    def __str__(self):
        return self.case_name

    class Meta:
        verbose_name = "测试用例"
        verbose_name_plural = "测试用例"


class Plan(models.Model):
    plan_id = models.AutoField(primary_key=True, null=False)
    plan_name = models.CharField(max_length=100)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    environment = models.ForeignKey(Environment, on_delete=models.CASCADE)
    description = models.CharField(max_length=200)
    content = models.TextField()
    report_name = models.CharField(max_length=255, default="")
    make = models.IntegerField(null=True)
    is_locust = models.IntegerField(default=0)  # 性能测试
    is_task = models.IntegerField(default=0)  # 定时任务
    update_time = models.DateTimeField('更新时间', auto_now=True)
    update_user = models.CharField(max_length=30, default='')

    def __str__(self):
        return self.plan_name

    class Meta:
        verbose_name = "测试计划"
        verbose_name_plural = "测试计划"


class Report(models.Model):
    report_id = models.AutoField(primary_key=True, null=False)
    report_name = models.CharField(max_length=255)
    report_path = models.CharField(max_length=255, default='', null=True)
    pic_name = models.CharField(max_length=255, default='')
    totalTime = models.CharField(max_length=50, default='')
    startTime = models.CharField(max_length=50, default='')
    plan = models.ForeignKey(Plan, on_delete=models.CASCADE, null=True)
    task = models.ForeignKey(PeriodicTask, on_delete=models.CASCADE, null=True)
    content = models.TextField()
    case_num = models.IntegerField(null=True)
    skip_num = models.IntegerField(null=True)
    pass_num = models.IntegerField(null=True)
    fail_num = models.IntegerField(null=True)
    error_num = models.IntegerField(null=True)
    update_time = models.DateTimeField('更新时间', auto_now=True)
    update_user = models.CharField(max_length=30, default='')
    make = models.IntegerField(null=True)

    def __str__(self):
        return self.report_name

    class Meta:
        verbose_name = "测试报告"
        verbose_name_plural = "测试报告"


# 发布会表
class Event(models.Model):
    name = models.CharField(max_length=100)  # 发布会标题
    limit = models.IntegerField()  # 参加人数
    status = models.BooleanField()  # 状态
    address = models.CharField(max_length=200)  # 地址
    start_time = models.DateTimeField('events time')  # 发布会时间
    create_time = models.DateTimeField(auto_now=True)  # 创建时间(自动获取当前时间)

    # admin中显示发布会名称
    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "发布会表"
        verbose_name_plural = "发布会表"


# 嘉宾表
class Guest(models.Model):
    event = models.ForeignKey(Event, related_name='guests', on_delete=models.CASCADE)  # 关联发布会id
    realname = models.CharField(max_length=64)  # 姓名
    phone = models.CharField(max_length=16)  # 手机号
    email = models.EmailField()  # 邮箱
    sign = models.BooleanField()  # 签到状态
    create_time = models.DateTimeField(auto_now=True)  # 创建时间(自动获取当前时间)

    class Meta:
        unique_together = ('event', 'phone')
        verbose_name = "嘉宾表"
        verbose_name_plural = "嘉宾表"

    # admin中显示嘉宾名称
    def __str__(self):
        return self.realname


# locust报告
class LocustReport(models.Model):
    id = models.AutoField(primary_key=True, null=False)
    current_response_time_percentile_50 = models.FloatField(default=0.0, null=True)
    current_response_time_percentile_95 = models.FloatField(default=0.0, null=True)
    fail_ratio = models.FloatField(default=0.0, null=True)
    total_rps = models.FloatField(default=0.0, null=True)
    user_count = models.IntegerField(default=0, null=True)
    errors = models.TextField()
    slaves = models.TextField()
    stats = models.TextField()
    state = models.CharField(max_length=50, default='')
    update_time = models.DateTimeField('更新时间', auto_now=True)
    update_user = models.CharField(max_length=30, default='')

    class Meta:
        verbose_name = "locust报告"
        verbose_name_plural = "locust报告"


class DebugTalk(models.Model):
    create_time = models.DateTimeField('创建时间', auto_now_add=True)
    update_time = models.DateTimeField('更新时间', auto_now=True)
    belong_project = models.ForeignKey(Project, on_delete=models.CASCADE, null=True)
    debugtalk = models.TextField(null=True, default='#debugtalk.py')
    status = models.BooleanField(default=False)  # 状态
    page = models.IntegerField(default=1, null=True)

    class Meta:
        verbose_name = '驱动py文件'
        db_table = 'DebugTalk'


class ModularTable(models.Model):
    url = models.CharField(max_length=255)
    Icon = models.CharField(max_length=255)
    model_name = models.CharField(max_length=255)

    def __str__(self):
        return self.model_name

    class Meta:
        verbose_name = "模块名称"
        verbose_name_plural = "模块名称"


class UserPower(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    power = models.CharField(max_length=255)

    def __str__(self):
        return self.user

    class Meta:
        verbose_name = "用户权限"
        verbose_name_plural = "用户权限"

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <title>EasyTest - 接口自动化测试平台</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <!-- VENDOR CSS -->
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <!-- MAIN CSS -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <!-- FOR DEMO PURPOSES ONLY. You should remove this in your project -->
    <link rel="stylesheet" href="{% static 'css/demo.css' %}">
    <link rel="stylesheet" href="{% static 'css/loading.css' %}">
    <!-- GOOGLE FONTS -->
    {#    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700" rel="stylesheet">#}
    <!-- ICONS -->
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'img/favicon.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'img/favicon.png' %}">
    <style type="text/css">
        body {
            background-image: "{% static 'img/bg.svg' %}";
            background-color: #F3F5F8;
        }

        #particles-js {
            position: fixed;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            z-index: -1;
        }

        #sidebar-nav .sidebar-scroll nav li {
            border-bottom: 1px solid rgba(107, 108, 109, 0.19);
        }

        .breadcrumb {
            background-color: transparent;
        }

        .breadcrumb li a {
            color: #777777;
            font-size: 18px;
            font-weight: 600;
        }

        .navbar .nav > li .dropdown-menu {
            margin: 0;
        }

        .navbar .nav > li:hover .dropdown-menu {
            display: block;
        }
    </style>
    {% block css %}{% endblock %}

</head>

<body>
<!-- WRAPPER -->
<div id="wrapper">
    <!-- NAVBAR -->
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="brand">
            <a href="{% url 'index' %}"><img src="{% static 'img/logo.png' %}" alt="Klorofil Logo"
                                             class="img-responsive logo"></a>
        </div>
        <div class="container-fluid">
            <div class="navbar-btn">
                <button type="button" class="btn-toggle-fullwidth"><i class="fa fa-arrow-left"></i></button>
            </div>
            <div id="navbar-menu1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown" onclick="select_ul()">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><img
                                src="{% static 'img/userImg.jpeg' %}"
                                class="img-circle" alt="Avatar">
                            <span>{{ user }}</span> <i class="icon-submenu fa fa-caret-down"></i></a>
                        <ul class="dropdown-menu">
                            <li><a href="javascript:void(0)" onclick="changePassword()"><i
                                    class="fa fa-minus-square"></i> <span>修改密码</span></a>
                            </li>
                            <li><a href="https://email.163.com/" target="_blank"><i class="fa fa-envelope-open"></i>
                                <span>163邮箱</span></a></li>
                            <li><a href="/admin/"><i class="fa fa-bookmark"></i> <span>管理后台</span></a></li>
                            <li><a href="{% url 'guest:event_manage' %}"><i
                                    class="fa fa-mouse-pointer"></i> <span>demo页面</span></a>
                            </li>
                            <li><a href="{% url 'mocks:mock_api' %}"><i
                                    class="fa fa-pinterest-square"></i> <span>Mocks服务</span></a>
                            </li>
                            {#                            <li><a href="http://www.easytest.xyz:8080" target="_blank"><i#}
                            {#                                    class="fa fa-rocket"></i> <span>jenkins部署</span></a>#}
                            {#                            </li>#}
                            <li><a href="http://www.easytest.xyz:8889/index" target="_blank"><i
                                    class="fa fa-compass"></i> <span>宝塔监控</span></a>
                            </li>
                            <li><a href="https://github.com/lixiaofeng1993/EasyTest" target="_blank"><i
                                    class="fa fa-github"></i> <span>Github地址</span></a>
                            </li>
                            <li><a href="https://www.cnblogs.com/changqing8023" target="_blank"><i
                                    class="fa fa-rouble"></i> <span>博客园地址</span></a>
                            </li>
                            <li><a href="{% url 'logout' %}"><i class="fa fa-sign-out"></i> <span>退出</span></a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div id="sidebar-nav" class="sidebar">
        <div class="sidebar-scroll">
            <nav>
                <ul class="nav" style="margin-top: 15px">
                    <li><a href="{% url 'index' %}" class=""><i class="fa fa-home"></i> <span
                            style="margin-left: 0">主页</span></a></li>
                    <li>
                        {% block nav %}

                        {% endblock %}
                        {#                    <li><a href="{% url 'base:project' %}" class=""><i class="fa fa-product-hunt fa-fw"></i>项目管理</a>#}
                        {#                    </li>#}
                        {#                    <li><a href="{% url 'base:env' %}" class=""><i class="fa fa-envira fa-fw"></i>测试环境</a>#}
                        {#                    </li>#}
                        {#                    <li><a href="{% url 'base:interface' %}" class=""><i#}
                        {#                            class="fa fa-pinterest-square fa-fw"></i>接口管理</a>#}
                        {#                    </li>#}
                        {#                    <li><a href="{% url 'base:case' %}" class=""><i class="fa fa-suitcase fa-fw"></i>用例管理</a>#}
                        {#                    </li>#}
                        {#                    <li><a href="{% url 'base:plan' %}" class=""><i class="fa fa-book fa-fw"></i>测试计划</a>#}
                        {#                    </li>#}
                        {#                    <li><a href="{% url 'base:task_index' %}" class=""><i class="fa fa-tasks fa-fw"></i>定时任务</a>#}
                        {#                    </li>#}
                        {#                    <li><a href="{% url 'base:report_page' %}" class=""><i class="fa fa-bar-chart fa-fw"></i>运行报告</a>#}
                        {#                    </li>#}
                        {#                    <li><a href="{% url 'base:performance' %}" class=""><i class="fa fa-book fa-fw"></i>性能测试</a>#}
                        {#                    <li><a href="{% url 'base:sign' %}" class=""><i class="fa fa-pencil fa-fw"></i>签名方式</a>#}
                        {#                    </li>#}
                        {#                    <li><a href="{% url 'base:user' %}" class=""><i class="fa fa-user fa-fw"></i>用户管理</a>#}
                        {#                    </li>#}
                        {#                    <li><a href="{% url 'base:about' %}" class=""> <i class="fa fa-cog fa-cab"></i> 关于我们</a></li>#}
                </ul>
            </nav>
        </div>
    </div>
    <!-- END LEFT SIDEBAR -->
    <!-- MAIN -->
    <div class="main">
        <div class="main-content">
            <div class="container-fluid">
                {% block crumbs %}
                {% endblock %}
                {% block body %}
                {% endblock %}
            </div>
        </div>
    </div>

</div>

<div id="particles-js"></div>

<script src="{% static 'jquery/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.slimscroll.min.js' %}"></script>
<script src="{% static 'js/klorofil-common.js' %}"></script>
<script type="application/javascript" src="{% static 'js/particles.js' %}"></script>
<script type="application/javascript" src="{% static 'js/app.js' %}"></script>
<script>
    $(document).ready(function () {
        var a_name = $("a").text();

        var page_name = $("a.this-page").text();
        console.log(page_name);
        if (a_name) {
            $("span:contains(" + a_name + ")").parent('a').removeClass("collapsed");
            $("span:contains(" + a_name + ")").parent('a').addClass("active");
            if (page_name) {
                $("a:contains(" + page_name + ")").parent('li').parent('ul').parent('div').removeClass("collapse");
                $("a:contains(" + page_name + ")").parent('li').parent('ul').parent('div').addClass("collapse in");
                $("a:contains(" + page_name + ")").addClass("active");
            }
        }
    });
    function changePassword() {
        var new_password = prompt('新密码');
        $.ajax({
            type: "post",
            url: "/change_password/",
            data: {
                "new_password": new_password
            },
            success: function (data) {
                if (new_password) {
                    if (data['msg'] == 'success') {
                        alert('修改密码成功！');
                        window.location.replace("/login_action/");
                    } else {
                        alert(data['msg'])
                    }
                } else if (new_password == '') {
                    alert('密码不能为空！')
                } else {
                    // 点击取消按钮
                }

            }
        })
    }
    function select_ul() {
        console.log(1);
        $(".dropdown").attr("class", "dropdown open");
        $("#img").attr("aria-expanded", "true");
    }

</script>

{% block javascript %} {% endblock %}
</body>

</html>