EasyTest/urls.py
from django.contrib import admin
# from django.urls import path
from django.conf.urls import include
# from EasyTest.views import index
from EasyTest import views
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

admin.site.site_header = 'EasyTest-后台管理'
admin.site.site_title = 'EasyTest-Manage'

urlpatterns = [

    url(r'admin/', admin.site.urls),
    url(r'^$', view=views.index, name="index"),
    url(r'index/$', view=views.index, name="index"),
    url(r'index_data/$', view=views.index_data, name="index_data"),
    url(r'^login_action/$', view=views.login_action, name='login_action'),
    url(r'^change_password/$', view=views.change_password, name='change_password'),
    url(r'^register/$', view=views.register, name='register'),
    url(r'^logout/$', view=views.logout, name='logout'),  # 退出
    url(r'^img_download/', view=views.img_download, name='img_download'),  # 下载图片
    url(r'^get_whether/', view=views.get_whether, name='get_whether'),  # 下载图片

    url(r'^base/', include("base.urls")),
    url(r'^api/', include('guest.urls')),  # api
    url(r'^mocks/', include('mocks.urls')),  # api

    url(r'^favicon.ico$', RedirectView.as_view(url=r'/static/img/E_fa.png')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler400 = views.bad_request
handler403 = views.permission_denied
handler404 = views.page_not_found
handler500 = views.server_error

base/urls.py
# !/usr/bin/env python
# coding=utf-8
# from django.conf import settings
from django.conf.urls import url
from django.urls import path
# from django.conf.urls.static import static
# from django.views.generic.base import RedirectView
from . import views

app_name = "base"
urlpatterns = [
    # 项目
    url(r'project/', view=views.ProjectIndex.as_view(), name='project'),
    url(r'project_add/', view=views.project_add, name='project_add'),
    url(r'project_update/', view=views.project_update, name='project_update'),
    url(r'project_delete/', view=views.project_delete, name='project_delete'),
    # 签名
    url(r'sign/', view=views.SignIndex.as_view(), name='sign'),
    url(r'sign_add/', view=views.sign_add, name='sign_add'),
    url(r'sign_update/', view=views.sign_update, name='sign_update'),
    url(r'sign_delete/', view=views.sign_delete, name='sign_delete'),
    # 测试环境
    url(r'env/', view=views.EnvIndex.as_view(), name='env'),
    url(r'env_add/', view=views.env_add, name='env_add'),
    url(r'env_update/', view=views.env_update, name='env_update'),
    url(r'env_delete/', view=views.env_delete, name='env_delete'),
    url(r'set_headers/', view=views.set_headers, name='set_headers'),
    # 接口
    url(r'interface/', view=views.InterfaceIndex.as_view(), name='interface'),
    url(r'interface_add/', view=views.interface_add, name='interface_add'),
    url(r'interface_update/', view=views.interface_update, name='interface_update'),
    url(r'interface_delete/', view=views.interface_delete, name='interface_delete'),
    url(r'interface_search/', view=views.interface_search, name='interface_search'),
    url(r'interface_copy/', view=views.interface_copy, name='interface_copy'),
    url(r'set_mock/', view=views.set_mock, name='set_mock'),
    # 用例
    url(r'case/', view=views.CaseIndex.as_view(), name='case'),
    url(r'case_add/', view=views.case_add, name='case_add'),
    url(r'case_update/', view=views.case_update, name='case_update'),
    url(r'case_delete/', view=views.case_delete, name='case_delete'),
    url(r'case_run/', view=views.case_run, name='case_run'),
    url(r'case_logs/', view=views.case_logs, name='case_logs'),
    url(r'case_copy/', view=views.case_copy, name='case_copy'),
    url(r'case_search/', view=views.case_search, name='case_search'),
    # 测试计划
    url(r'plan/', view=views.PlanIndex.as_view(), name='plan'),
    url(r'plan_add/', view=views.plan_add, name='plan_add'),
    url(r'plan_update/', view=views.plan_update, name='plan_update'),
    url(r'plan_delete/', view=views.plan_delete, name='plan_delete'),
    url(r'plan_run/', view=views.plan_run, name='plan_run'),
    # 报告
    url(r'^report/', view=views.report_index, name='report'),
    url(r'report_search/', view=views.report_search, name='report_search'),
    # 异步请求获取数据
    url(r'findata/', view=views.findata, name='findata'),
    # 批量导入
    url(r'batch_index', view=views.batch_index, name='batch_index'),
    # 定时任务
    url(r'task/', view=views.TaskIndex.as_view(), name='task'),
    url(r'task_run/', view=views.task_run, name='task_run'),
    url(r'task_logs/', view=views.task_logs, name='task_logs'),
    url(r'task_add/', view=views.task_add, name='task_add'),
    url(r'task_update/', view=views.task_update, name='task_update'),
    url(r'task_delete/', view=views.task_delete, name='task_delete'),
    # 报告页面展示
    url(r'report_page/', view=views.ReportPage.as_view(), name='report_page'),
    url(r'report_logs/', view=views.report_logs, name='report_logs'),  # 日志
    url(r'report_delete/', view=views.report_delete, name='report_delete'),
    url(r'report_results/', view=views.report_results, name='report_results'),  # 获取报告执行结果
    # locust
    url(r'performance/', view=views.performance_index, name='performance'),
    url(r'start_locust/', view=views.start_locust, name='start_locust'),
    url(r'performance_report/', view=views.performance_report, name='performance_report'),
    url(r'performance_real/', view=views.performance_real, name='performance_real'),
    url(r'performance_history/', view=views.performance_history, name='performance_history'),
    url(r'performance_delete/', view=views.performance_delete, name='performance_delete'),
    url(r'performance_status/', view=views.performance_status, name='performance_status'),
    # 下载
    url(r'file_download/', view=views.file_download, name='file_download'),
    # 添加用户
    url(r'user/', view=views.UserIndex.as_view(), name='user'),
    url(r'user_power/', view=views.user_power, name='user_power'),
    # 关于我们
    url(r'about/', view=views.about_index, name='about'),
    url(r'document/', view=views.document, name='document'),
    url(r'debugtalk/', view=views.debugtalk, name='debugtalk'),
    url(r'love/', view=views.love, name='love'),
]

base/views.py
# -*- coding: utf-8 -*-
import os, time, json, logging, threading, platform, re, zipfile, requests
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from .tasks import delete_logs, run_plan, stop_locust, test_httprunner, test_plan
from django.http import StreamingHttpResponse
from base.models import Project, Sign, Environment, Interface, Case, Plan, Report, LocustReport, DebugTalk, \
    ModularTable, UserPower
from django.contrib.auth.models import User  # django自带user
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.db.models import Q  # 与或非 查询
from lib.execute import Test_execute, get_user, is_superuser, limits_of_authority  # 执行接口
from djcelery.models import PeriodicTask, CrontabSchedule, IntervalSchedule, PeriodicTasks
from datetime import timedelta, datetime
from lib.swagger import AnalysisJson
from django.shortcuts import render_to_response
# from base.page_cache import page_cache  # redis缓存
from lib.public import DrawPie, paginator, pagination_data
from lib.error_code import ErrorCode
from lib.except_check import project_info_logic, sign_info_logic, env_info_logic, interface_info_logic, format_params, \
    case_info_logic, plan_info_logic, header_value_error  # 自定义异常逻辑
from django.views.generic import ListView
from django.conf import settings
from lib.helper import delete_performance, copy_debugtalk

# import paramiko
# from stat import S_ISDIR as isdir
# from lib import readConfig

log = logging.getLogger('log')  # 初始化log
logs_path = os.path.join(os.getcwd(), 'logs')  # 拼接删除目录完整路径
start_time = ''  # 执行测试计划开始时间
totalTime = ''  # 执行测试计划运行时间
now_time = ''  # 饼图命名区分
class_name = ''  # 执行测试类


# 项目列表
# @page_cache(5)
@method_decorator(login_required, name='dispatch')
class ProjectIndex(ListView):
    model = Project
    template_name = 'base/project/index.html'
    context_object_name = 'object_list'
    paginate_by = 10

    def dispatch(self, *args, **kwargs):
        return super(ProjectIndex, self).dispatch(*args, **kwargs)

    def get_queryset(self):
        project_list = Project.objects.all().order_by('-prj_id')
        return project_list
        # superuser = User.objects.get(id=user_id).is_superuser
        # if superuser:
        #     return Project.objects.all().order_by('-prj_id')
        # else:
        #     return Project.objects.filter(user_id=user_id).order_by('-prj_id')

    def get_context_data(self, **kwargs):
        self.page = self.request.GET.dict().get('page', '1')
        context = super().get_context_data(**kwargs)
        paginator = context.get('paginator')
        page = context.get('page_obj')
        is_paginated = context.get('is_paginated')
        data = pagination_data(paginator, page, is_paginated)
        context.update(data)
        user_id = self.request.session.get('user_id', '')
        model_list = limits_of_authority(user_id)
        context.update({"model_list": model_list, "page": self.page})
        return context


def project_add(request):
    """
    增加项目
    :param request:
    :return:
    """
    user_id = request.session.get('user_id', '')
    if not get_user(user_id):
        request.session['login_from'] = '/base/project/'
        return render(request, 'user/login_action.html')
    else:
        sign_list = Sign.objects.all()  # 所有签名
        model_list = limits_of_authority(user_id)
        if request.method == 'POST':
            prj_name = request.POST['prj_name'].strip()

            msg = project_info_logic(prj_name)
            if msg != 'ok':  # 判断输入框
                log.error('project add error：{}'.format(msg))
                info = {'error': msg, "sign_list": sign_list, "model_list": model_list, "page": "1"}
                return render(request, 'base/project/add.html', info)
            else:
                description = request.POST['description']
                sign_id = request.POST['sign']
                sign = Sign.objects.get(sign_id=sign_id)
                user = User.objects.get(id=user_id)
                prj = Project(prj_name=prj_name, description=description, sign=sign, user=user)
                prj.save()
                log.info('add project   {}  success. project info: {} // {} '.format(prj_name, description, sign))
                return HttpResponseRedirect("/base/project/")
        elif request.method == 'GET':
            if not sign_list:
                querysetlist = []
                sign_dict = [{"id": 1, "name": "不签名", "type": "无"}, {"id": 2, "name": "md5加密", "type": "md5加密"},
                             {"id": 3, "name": "用户认证", "type": "用户认证"}, {"id": 4, "name": "AES算法", "type": "AES算法"}]
                for signer in sign_dict:
                    querysetlist.append(
                        Sign(sign_id=signer["id"], sign_name=signer["name"], sign_type=signer["type"], description="",
                             update_time=datetime.now(), update_user="root"))
                Sign.objects.bulk_create(querysetlist)
                sign_list = Sign.objects.all()
            info = {"sign_list": sign_list, "model_list": model_list}
            return render(request, "base/project/add.html", info)


def project_update(request):
    """
    项目编辑
    :param request:
    :return:
    """
    user_id = request.session.get('user_id', '')
    if not get_user(user_id):
        request.session['login_from'] = '/base/project/'
        return render(request, 'user/login_action.html')
    else:
        sign_list = Sign.objects.all()
        model_list = limits_of_authority(user_id)
        if request.method == 'POST':
            prj_id = request.POST['prj_id']
            page = request.POST['page']
            prj_name = request.POST['prj_name'].strip()

            msg = project_info_logic(prj_name, prj_id)
            if msg != 'ok':
                log.error('project update error：{}'.format(msg))
                prj = Project.objects.get(prj_id=prj_id)
                info = {'error': msg, "prj": prj, "sign_list": sign_list, "model_list": model_list, "page": page}
                return render(request, 'base/project/update.html', info)
            else:
                description = request.POST['description']
                sign_id = request.POST['sign_id']
                sign = Sign.objects.get(sign_id=sign_id)
                user = User.objects.get(id=user_id)
                Project.objects.filter(prj_id=prj_id).update(prj_name=prj_name, description=description, sign=sign,
                                                             user=user, update_time=datetime.now())
                log.info('edit project   {}  success. project info: {} // {} '.format(prj_name, description, sign))
                return HttpResponseRedirect("/base/project/?page={}".format(page))
        elif request.method == 'GET':
            prj_id = request.GET['prj_id']
            page = request.GET.get("page", "1")
            user_id_belong = Project.objects.get(prj_id=prj_id).user_id
            if user_id == user_id_belong:
                prj = Project.objects.get(prj_id=prj_id)
                info = {"prj": prj, "sign_list": sign_list, "model_list": model_list, "page": page}
                return render(request, "base/project/update.html", info)
            else:
                info = {'error': '非本人创建项目，不可以修改！', "model_list": model_list}
                return render(request, "base/project/update.html", info)


def project_delete(request):
    """
    删除项目
    :param request:
    :return:
    """
    user_id = request.session.get('user_id', '')
    if not get_user(user_id):
        request.session['login_from'] = '/base/project/'
        return render(request, 'user/login_action.html')
    else:
        if request.method == 'GET':
            prj_id = request.GET['prj_id']
            page = request.GET.get("page", "1")
            project = Project.objects.filter(prj_id=prj_id)
            project.delete()
            is_page = project.count() % 10
            if not is_page and int(page) > 1:
                page = int(page) - 1
            log.info('用户 {} 删除项目 {} 成功.'.format(user_id, prj_id))
            return HttpResponseRedirect("base/project/?page={}".format(page))


# 签名列表
# @page_cache(5)
@method_decorator(login_required, name='dispatch')
class SignIndex(ListView):
    model = Sign
    template_name = 'system/sign/sign_index.html'
    context_object_name = 'object_list'
    paginate_by = 10

    def dispatch(self, *args, **kwargs):
        return super(SignIndex, self).dispatch(*args, **kwargs)

    def get_queryset(self):
        sign_list = Sign.objects.all().order_by("-sign_id")
        return sign_list

    def get_context_data(self, **kwargs):
        self.page = self.request.GET.dict().get('page', '1')
        context = super().get_context_data(**kwargs)
        paginator = context.get('paginator')
        page = context.get('page_obj')
        is_paginated = context.get('is_paginated')
        data = pagination_data(paginator, page, is_paginated)
        context.update(data)
        user_id = self.request.session.get('user_id', '')
        model_list = limits_of_authority(user_id)
        context.update({"model_list": model_list, "page": self.page})
        return context


def sign_add(request):
    """
    添加签名
    :param request:
    :return:
    """
    user_id = request.session.get('user_id', '')
    if not get_user(user_id):
        request.session['login_from'] = '/base/sign/'
        return render(request, 'user/login_action.html')
    else:
        model_list = limits_of_authority(user_id)
        if request.method == 'POST':
            sign_name = request.POST['sign_name'].strip()
            sign_type = request.POST['sign_type'].strip()

            msg = sign_info_logic(sign_name)
            if msg != 'ok':
                log.error('sign add error：{}'.format(msg))
                info = {'error': msg, "model_list": model_list, "page": "1"}

templates/base/report_page/report_page.html
{% extends "base.html" %}

{% block css %}
    <style>
        #cen {
            text-align: center;
        }

        a:hover {
            color: red;
        }

        .env-name {
            max-width: 200px;
            word-wrap: break-word;
            text-overflow: ellipsis;
            white-space: nowrap;
            overflow: hidden;
        }

        .env-name:hover {
            white-space: normal;
            overflow: auto;
        }

        tr:hover {
            background-color: #e7e7e7;
        }
    </style>
{% endblock %}

{% block nav %}
    {% for foo in model_list %}
        <li><a href="{{ foo.url }}"><i class="{{ foo.icon }}"></i>{{ foo.model_name }}</a>
        </li>
    {% endfor %}

{% endblock %}

{% block crumbs %}
    <div class="row">
        <div class="col-md-12">
            <ol class="breadcrumb">
                <li class="active">
                    <a class="this-page" href="{% url 'base:report_page' %}">运行报告</a>
                </li>
            </ol>

        </div>
    </div>
{% endblock %}

{% block body %}

    <div class="row">
        <div class="col-md-12">
            <div class="panel">
                <div class="panel-body">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th id="cen">ID</th>
                            <th id="cen">测试报告名称</th>
                            <th id="cen">运行时长</th>
                            <th id="cen">用例数量</th>
                            <th id="cen">接口通过数量</th>
                            <th id="cen">接口失败数量</th>
                            <th id="cen">接口错误数量</th>
                            <th id="cen">所属计划/任务</th>
                            <th id="cen">创建时间</th>
                            <th id="cen">创建用户</th>
                            <th id="cen">操作</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for env in object_list %}
                            <tr>
                                <td id="cen" class="report_id">{{ env.report_id }}</td>
                                {% ifequal env.make 1 %}
                                    {% if env.error_num %}
                                        <td class="env-name"
                                            style="background-color: #FFECF5">{{ env.report_name }}</td>
                                    {% else %}
                                        {% if env.fail_num %}
                                            <td class="env-name"
                                                style="background-color: #FFFFDF">{{ env.report_name }}</td>
                                        {% else %}
                                            <td class="env-name"
                                                style="background-color: #ECFFFF">{{ env.report_name }}</td>
                                        {% endif %}
                                    {% endif %}

                                {% else %}
                                    <td class="env-name">{{ env.report_name }}</td>
                                {% endifequal %}
                                <td id="cen">{{ env.totalTime }}</td>
                                <td id="cen">{{ env.case_num }}</td>
                                <td id="cen">{{ env.pass_num }}</td>
                                <td id="cen">{{ env.fail_num }}</td>
                                <td id="cen">{{ env.error_num }}
                                    {% if env.plan %}
                                        <td id="cen" class="env-name">{{ env.plan }}</td>
                                    {% else %}
                                        <td id="cen" class="env-name">{{ env.task }}</td>
                                    {% endif %}
                                <td id="cen">{{ env.update_time }}</td>
                                <td id="cen">{{ env.update_user }}</td>
                                <td id="cen">
                                    <a href="{% url 'base:report' %}?report_id={{ env.report_id }}&&page={{ page }}"
                                       class="layui-btn layui-btn-danger layui-btn-xs">
                                        <i class="fa fa-bar-chart"></i>&nbsp;&nbsp;&nbsp;
                                    </a>
                                    <a href="{% url 'base:report_logs' %}?report_id={{ env.report_id }}"
                                       class="layui-btn layui-btn-danger layui-btn-xs">
                                        <i class="fa fa-file-text-o"></i>&nbsp;&nbsp;&nbsp;</a>
                                    {% ifequal env.make 1 %}
                                        <a href="{% url 'base:file_download' %}?report_id={{ env.report_id }}"
                                           class="layui-btn layui-btn-danger layui-btn-xs"
                                           onclick="return download_btn()"><i
                                                class="fa fa-cloud-download"></i>&nbsp;
                                        </a>
                                    {% endifequal %}

                                    <a href="{% url 'base:report_delete' %}?report_id={{ env.report_id }}&&page={{ page }}"
                                       class="layui-btn layui-btn-danger layui-btn-xs"
                                       onclick="return delete_btn()"><img
                                            src="/static/admin/img/icon-deletelink.svg"/>&nbsp;&nbsp;&nbsp;
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    {% if url %}
                        <p style="font-size: 20px;font-weight: 700;">点击链接下载报告：<a href="{{ url }}">{{ url }}</a></p>
                    {% endif %}
                    <span style="color: red; font-size: 12px">{{ error }}</span>
                </div>
                {% if is_paginated %}
                    <ul class="pagination">
                        {% if first %}
                            <li class="page"><a href="?plan_id={{ plan_id }}&page=1">1</a></li>
                        {% endif %}
                        {% if left %}
                            {% if left_has_more %}
                                <li class="page"><a href="javascript:void(0)">...</a></li>
                            {% endif %}
                            {% for i in left %}
                                <li class="page"><a href="?plan_id={{ plan_id }}&page={{ i }}">{{ i }}</a></li>
                            {% endfor %}
                        {% endif %}
                        <li class="page"><a href="javascript:void(0)" class="active"> {{ page_obj.number }}</a></li>
                        {% if right %}
                            {% for i in right %}
                                <li class="page"><a href="?plan_id={{ plan_id }}&page={{ i }}">{{ i }}</a></li>
                            {% endfor %}
                            {% if right_has_more %}
                                <li class="page"><a href="javascript:void(0)">...</a></li>
                            {% endif %}
                        {% endif %}
                        {% if last %}
                            <li class="page"><a
                                    href="?plan_id={{ plan_id }}&page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>
                            </li>
                        {% endif %}

                    </ul>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

{% block javascript %}
    <script>
        //删除
        function delete_btn() {
            if (window.confirm("你确定要删除吗？")) {
                return true;//确定返回真
            }
            else {
                return false;//取消返回假
            }
        }
        //删除
        function download_btn() {
            if (window.confirm("下载HttpRunner报告前，请先执行测试计划~~~")) {
                return true;//确定返回真
            }
            else {
                return false;//取消返回假
            }
        }
    </script>
{% endblock %}